export const SET_LOADING = "SET_LOADING"
export const SET_NEWS = "SET_NEWS"
export const REMOVE_ITEM = "REMOVE_ITEM"
export const HANDLE_SEARCH = "HANDLE_SEARCH"
export const HANDLE_PAGE = "HANDLE_PAGE"